image: alpine:latest

variables:
  PORT_CLIENT_ID: $PORT_CLIENT_ID
  PORT_CLIENT_SECRET: $PORT_CLIENT_SECRET
  DATADOG_API_KEY: $DATADOG_API_KEY
  DATADOG_APPLICATION_KEY: $DATADOG_APPLICATION_KEY

stages:
  - build

ingest_datadog_apm_to_port_job:
  stage: build
  before_script:
    - apk update && apk add curl jq
  script:
    - echo "Getting Datadog Service APM"
    - sh app.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always